version: "3.8"
services:
  app:
    build:
      context: ../
      dockerfile: ./.hub/Dockerfile
    restart: always
    volumes:
      - ..:/usr/src/app
      - /usr/src/app/node_modules/
    command:
      - /bin/sh
      - -c
      - |
        node ./.hub/tests/pre-test.cjs